### PR TITLE
Fix delete command

### LINKED ISSUE #76: Fix delete command
Currently, when using delete command on senior, it removes the senior from the caregiver. However, when delete command on caregiver, it does not remove caregiver from senior.

### PR DESCRIPTION
**Pull request by weihan-01**
Fix #76 

Currently what happens is that delete command removes person from person list. the senior is removed from a list of seniors of a caregiver. however, the caregiver still remains an attribute of the senior. the changes of this pr sets the caregiver of the senior to null, and thus the caregiver of a senior will now display as unassigned once that caregiver is deleted.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -9,7 +9,9 @@
 import seedu.address.logic.Messages;
 import seedu.address.logic.commands.exceptions.CommandException;
 import seedu.address.model.Model;
+import seedu.address.model.person.Caregiver;
 import seedu.address.model.person.Person;
+import seedu.address.model.person.Senior;
 
 /**
  * Deletes a person identified using it's displayed index from the address book.
```
Comment (whchenyicn) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java]: Perhaps could mention special handing of caregiver here, and changing "it's" to "its" may sound clearer

**Review by yymeiting — COMMENTED** [review]
Overall good fix! Thanks for updating delete command. Code is clean and easy to read
